name: Flutter CI/CD
permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # This will trigger the workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29'
          channel: 'stable'
          cache: true

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          export GRADLE_OPTS="-Xmx4g -XX:MaxMetaspaceSize=512m"
          flutter build apk --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install gh -y

      - name: Prepare variables
        id: vars
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "repo=oyounis19/GP-Tour-Guide" >> $GITHUB_OUTPUT

      - name: Upload Release to Other Repo
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            "release-apk/app-release.apk" \
            --repo "${{ steps.vars.outputs.repo }}" \
            --title "Release ${{ steps.vars.outputs.version }}" \
            --notes "Automated release for version ${{ steps.vars.outputs.version }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-apk
      # Your existing deployment steps