name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Set Android namespace
        run: |
          echo "android {
            namespace 'com.example.flutter_vision'
          }" >> android/app/build.gradle
          
          # Also add namespace to the flutter_vision module if it exists
          if [ -f "./flutter_vision/android/build.gradle" ]; then
            echo "android {
              namespace 'com.example.flutter_vision'
            }" >> ./flutter_vision/android/build.gradle
          fi

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-apk